table 'Ledger Entry'
	lineageTag: bc2fb743-1644-43be-8cde-b1a8e419cc65

	column 'Entry No_'
		dataType: int64
		formatString: 0
		lineageTag: 87c56fc9-e284-4e19-9c47-547f6a0dc577
		summarizeBy: sum
		sourceColumn: Entry No_

		annotation SummarizationSetBy = Automatic

	column 'Cust_ Ledger Entry No_'
		dataType: int64
		formatString: 0
		lineageTag: e7b56228-15f5-47ed-a437-c25b33dc8db0
		summarizeBy: sum
		sourceColumn: Cust_ Ledger Entry No_

		annotation SummarizationSetBy = Automatic

	column 'Entry Type'
		dataType: int64
		formatString: 0
		lineageTag: 904b18a1-7cb9-4001-a071-32ac24775bef
		summarizeBy: sum
		sourceColumn: Entry Type

		annotation SummarizationSetBy = Automatic

	column 'Posting Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a71183fa-c3ea-4b4d-8541-400f179a4d61
		summarizeBy: none
		sourceColumn: Posting Date

		variation Variation
			isDefault
			relationship: a8e6abf4-7c58-4025-8ce2-67cd678d7553
			defaultHierarchy: LocalDateTable_80088d8b-1a0c-4ca7-a86f-da5daf573c38.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Document Type'
		dataType: int64
		formatString: 0
		lineageTag: ae328a27-f0f4-44c8-802d-84775a39227a
		summarizeBy: sum
		sourceColumn: Document Type

		annotation SummarizationSetBy = Automatic

	column 'Document No_'
		dataType: string
		lineageTag: 517ab627-9453-4d38-aa9e-cb748d8de699
		summarizeBy: none
		sourceColumn: Document No_

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: c72b3941-579e-4453-b615-3988f8ecff97
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amount (LCY)'
		dataType: double
		lineageTag: e92cc85b-54c0-47d5-adc9-82cee5379d33
		summarizeBy: sum
		sourceColumn: Amount (LCY)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer No_'
		dataType: string
		lineageTag: 411eba82-32fa-4baf-aa98-9394aa42bc88
		summarizeBy: none
		sourceColumn: Customer No_

		annotation SummarizationSetBy = Automatic

	column 'Currency Code'
		dataType: string
		lineageTag: 2d30d29d-53ed-43a4-9c4e-d3863750f2e1
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'User ID'
		dataType: string
		lineageTag: d29370e5-29a6-43d0-8f14-64f8654c63ba
		summarizeBy: none
		sourceColumn: User ID

		annotation SummarizationSetBy = Automatic

	column 'Source Code'
		dataType: string
		lineageTag: 7d72bccb-ebdf-4c50-8261-54ffec5b703d
		summarizeBy: none
		sourceColumn: Source Code

		annotation SummarizationSetBy = Automatic

	column 'Transaction No_'
		dataType: int64
		formatString: 0
		lineageTag: f7ed0743-79e5-4df9-9628-5ac35dcbe651
		summarizeBy: sum
		sourceColumn: Transaction No_

		annotation SummarizationSetBy = Automatic

	column 'Journal Batch Name'
		dataType: string
		lineageTag: 09405ad7-fcad-4b2b-83f2-c6e6fd1541dc
		summarizeBy: none
		sourceColumn: Journal Batch Name

		annotation SummarizationSetBy = Automatic

	column 'Reason Code'
		dataType: string
		lineageTag: f827f4ff-9214-44a3-8fe2-59afb0be3374
		summarizeBy: none
		sourceColumn: Reason Code

		annotation SummarizationSetBy = Automatic

	column 'Debit Amount'
		dataType: int64
		formatString: 0
		lineageTag: f8fb5258-44ba-483b-a573-b0e567fe4a57
		summarizeBy: sum
		sourceColumn: Debit Amount

		annotation SummarizationSetBy = Automatic

	column 'Credit Amount'
		dataType: double
		lineageTag: 49db0bbe-02b5-451a-9a45-6ce901d1b6e9
		summarizeBy: sum
		sourceColumn: Credit Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Debit Amount (LCY)'
		dataType: int64
		formatString: 0
		lineageTag: fec7565c-5e8c-4ee6-8107-e9e2b03c143c
		summarizeBy: sum
		sourceColumn: Debit Amount (LCY)

		annotation SummarizationSetBy = Automatic

	column 'Credit Amount (LCY)'
		dataType: double
		lineageTag: b05ee0bb-68d4-42d4-812d-48c3d12fa4b9
		summarizeBy: sum
		sourceColumn: Credit Amount (LCY)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Initial Entry Due Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 40cc98eb-b14f-418e-806e-4206d7aec95a
		summarizeBy: none
		sourceColumn: Initial Entry Due Date

		variation Variation
			isDefault
			relationship: 8df03126-d51d-49fd-99cc-e885d2c2e936
			defaultHierarchy: LocalDateTable_c4941eb2-8983-4c69-831a-9143293bdf8d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Initial Entry Global Dim_ 1'
		dataType: string
		lineageTag: cd04ca8c-bed7-44d0-92d5-1165bf629f21
		summarizeBy: none
		sourceColumn: Initial Entry Global Dim_ 1

		annotation SummarizationSetBy = Automatic

	column 'Initial Entry Global Dim_ 2'
		dataType: string
		lineageTag: ed5fa03a-9d6d-4961-8814-ed6050be412b
		summarizeBy: none
		sourceColumn: Initial Entry Global Dim_ 2

		annotation SummarizationSetBy = Automatic

	column 'Gen_ Bus_ Posting Group'
		dataType: string
		lineageTag: 63815ea0-93d7-4f81-a21a-2a463bf1cc2a
		summarizeBy: none
		sourceColumn: Gen_ Bus_ Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Gen_ Prod_ Posting Group'
		dataType: string
		lineageTag: 376a8673-b992-47d3-b22e-84b149a60e83
		summarizeBy: none
		sourceColumn: Gen_ Prod_ Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Use Tax'
		dataType: int64
		formatString: 0
		lineageTag: 193a53a9-7e5f-49e5-804e-8d34990c98b5
		summarizeBy: sum
		sourceColumn: Use Tax

		annotation SummarizationSetBy = Automatic

	column 'VAT Bus_ Posting Group'
		dataType: string
		lineageTag: cbaaafaf-503d-4895-a09e-6b933f831450
		summarizeBy: none
		sourceColumn: VAT Bus_ Posting Group

		annotation SummarizationSetBy = Automatic

	column 'VAT Prod_ Posting Group'
		dataType: string
		lineageTag: fdf2563c-70ab-464b-b4ba-3d84fe084b24
		summarizeBy: none
		sourceColumn: VAT Prod_ Posting Group

		annotation SummarizationSetBy = Automatic

	column 'Initial Document Type'
		dataType: int64
		formatString: 0
		lineageTag: 77907386-88e9-4eb1-b84e-2849d05fe561
		summarizeBy: sum
		sourceColumn: Initial Document Type

		annotation SummarizationSetBy = Automatic

	column 'Applied Cust_ Ledger Entry No_'
		dataType: int64
		formatString: 0
		lineageTag: d9703e75-5ef6-4924-9a14-1d199f4ab26c
		summarizeBy: sum
		sourceColumn: Applied Cust_ Ledger Entry No_

		annotation SummarizationSetBy = Automatic

	column Unapplied
		dataType: int64
		formatString: 0
		lineageTag: 2f2485ba-9a40-4579-82fe-630acfcb4528
		summarizeBy: sum
		sourceColumn: Unapplied

		annotation SummarizationSetBy = Automatic

	column 'Unapplied by Entry No_'
		dataType: int64
		formatString: 0
		lineageTag: d94a4c91-089b-421b-8f42-a3d8b436a65d
		summarizeBy: sum
		sourceColumn: Unapplied by Entry No_

		annotation SummarizationSetBy = Automatic

	column 'Remaining Pmt_ Disc_ Possible'
		dataType: int64
		formatString: 0
		lineageTag: b4403ff5-f473-4f10-b7d7-2426b7d85bee
		summarizeBy: sum
		sourceColumn: Remaining Pmt_ Disc_ Possible

		annotation SummarizationSetBy = Automatic

	column 'Max_ Payment Tolerance'
		dataType: int64
		formatString: 0
		lineageTag: b3a152d4-e2f5-4c77-9214-76032153f20f
		summarizeBy: sum
		sourceColumn: Max_ Payment Tolerance

		annotation SummarizationSetBy = Automatic

	column 'Tax Jurisdiction Code'
		dataType: string
		lineageTag: f8f6120e-059d-4c4c-8f5a-2061ef276e44
		summarizeBy: none
		sourceColumn: Tax Jurisdiction Code

		annotation SummarizationSetBy = Automatic

	column 'Application No_'
		dataType: int64
		formatString: 0
		lineageTag: d7be03ac-c0eb-4d2f-a434-7e8b72079b15
		summarizeBy: sum
		sourceColumn: Application No_

		annotation SummarizationSetBy = Automatic

	column 'Ledger Entry Amount'
		dataType: int64
		formatString: 0
		lineageTag: b74c5aaf-522a-4408-8e6a-1cc2ba4254cf
		summarizeBy: sum
		sourceColumn: Ledger Entry Amount

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 92e057c3-2246-4933-932a-11612e4cd56c
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	partition 'Ledger Entry' = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\Lenovo\Downloads\FT2324381H52 INVOICE APPLICATIONS BACKUP.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Sheet1", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"timestamp", type text}, {"Entry No_", Int64.Type}, {"Cust_ Ledger Entry No_", Int64.Type}, {"Entry Type", Int64.Type}, {"Posting Date", type datetime}, {"Document Type", Int64.Type}, {"Document No_", type text}, {"Amount", type number}, {"Amount (LCY)", type number}, {"Customer No_", type text}, {"User ID", type text}, {"Source Code", type text}, {"Transaction No_", Int64.Type}, {"Debit Amount", Int64.Type}, {"Credit Amount", type number}, {"Debit Amount (LCY)", Int64.Type}, {"Credit Amount (LCY)", type number}, {"Initial Entry Due Date", type datetime}, {"Initial Entry Global Dim_ 1", type text}, {"Initial Entry Global Dim_ 2", type text}, {"Use Tax", Int64.Type}, {"Initial Document Type", Int64.Type}, {"Applied Cust_ Ledger Entry No_", Int64.Type}, {"Unapplied", Int64.Type}, {"Unapplied by Entry No_", Int64.Type}, {"Remaining Pmt_ Disc_ Possible", Int64.Type}, {"Max_ Payment Tolerance", Int64.Type}, {"Application No_", Int64.Type}, {"Ledger Entry Amount", Int64.Type}}, "en-US"),
				  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"timestamp"}),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Removed columns", {{"Posting Date", type date}}),
				  #"Inserted conditional column" = Table.AddColumn(#"Changed column type 1", "Month Name", each if [Posting Date] = #date(2023, 8, 31) then "August" else if [Posting Date] = #date(2023, 9, 4) then "September" else "Unknown")
				in
				  #"Inserted conditional column"

	annotation PBI_ResultType = Table

